### PR TITLE
Redesgined entities

### PR DESCRIPTION
**Pull request by VijayS02**
Built the project again from the ground up with the team, worked on code in real life with members.

### CODE REVIEW

**Review by akashilangovan — APPROVED** [review]
looks good to me

**Review by stephlum — APPROVED** [review]
Worked on code together, looks good.

**Review by kathybguo — APPROVED** [review]
Everything looks good

**Review by avi868 — APPROVED** [review]
looks good

**Review by jeremiahwong007 — APPROVED** [review]
Looks good

**Comment by JeffeyL** [comment]
Should there be javadocs inserted later? Looks good otherwise

**Pull request merged**
